### ISSUE TITLE
Recent CC update breaks this mod

### ISSUE THREAD

**Issue by misaka18848** [SamsTheNerd/ducky-periphs#46] opened 2024-11-11 11:04 UTC
I update CC:Tweaked to 1.113.1 then game will stack when i open old world.

**Comment by SamsTheNerd** [comment] 2024-11-11 22:35
do you happen to have an error log on hand?

**Comment by misaka18848** [comment] 2024-11-12 02:02
[minecraft-exported-logs-2024-11-11T16-05-08.log](https://github.com/user-attachments/files/17710133/minecraft-exported-logs-2024-11-11T16-05-08.log)

**Comment by SamsTheNerd** [comment] 2024-11-12 21:20
I'm not seeing much there involving ducky crashing? I'll have to look into it more. Are you sure that's the right crash log? Also is it only happening on old worlds or does it crash on new worlds as well?

**Comment by SamsTheNerd** [comment] 2024-11-26 07:19
i cannot reproduce this on latest CC:T, so going to assume whatever it was was either unrelated to ducky or fixed in newest CC release. Feel free to reopen if the issue persists and you can get steps to reproduce it.

**Closed by SamsTheNerd** 2024-11-26 07:19 UTC
Labels: bug
