### ISSUE TITLE
straight up breaks mining anything at all with a pickaxe

### ISSUE THREAD

**Issue by cloby0** [SamsTheNerd/ducky-periphs#52] opened 2024-12-07 19:59 UTC
when using the attached mods, you cannot mine anything with a pickaxe
this is because the mod tries to add `ducky-periphs:focal_link_block` to `minecraft:mineable/pickaxe`, when that isn't the name of a block in the mod
the block most likely being referenced is `ducky-periphs:focal_port_block`

steps to reproduce:
1. install the list of mods attached at the bottom, and none more (lmft or something would fix this)
2. load into a world
3. observe the logs saying that the `minecraft:mineable/pickaxe` tag has failed to load
4. attempt to mine stone with a diamond pickaxe

mods:
Architectury [9.2.14]
CC: Tweaked [1.113.1]
Caelus API [3.2.0+1.20.1]
Cloth Config v10 API [11.1.136]
Ducky Peripherals [1.20.1-1.3.1]
Hex Casting [0.11.2]
Inline [1.20.1-1.0.2]
Kotlin for Forge [5402061]
PAUCAL [0.6.0+1.20.1-forge]
Patchouli [1.20.1-84-FORGE]

**Comment by SamsTheNerd** [comment] 2024-12-07 20:59
Duplicate of #40

**Closed as completed** 2024-12-07 20:59 UTC
